### ISSUE TITLE
NameError: name 'string' is not defined

### ISSUE THREAD

**Issue by tuutoo** [swimlane/python-office365#2]
```bash
(venv-3.5.2) [root@vultr python3-office365]# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from office365api import __version__ as _version
  File "./office365api/__init__.py", line 1, in <module>
    from office365api.mail import Mail
  File "./office365api/mail/__init__.py", line 1, in <module>
    from office365api.mail.mail import Mail
  File "./office365api/mail/mail.py", line 1, in <module>
    from office365api.mail.base import Base
  File "./office365api/mail/base.py", line 9, in <module>
    class Base(Api):
  File "./office365api/mail/base.py", line 135, in Base
    def update_message(self, id: string, fields: dict):
NameError: name 'string' is not defined
```
For the master branch, when I try to install with python3 (Python 3.5.2), got above error.
I guess it's a typo, the 'string' should be 'str'?

**Comment by dmikov** [comment]
yes

**Comment by Pritam-007** [comment]
I have same kind of problem.
but I resolve it....
You can use "import string"
before using string

**Comment by QloudXee** [comment]
yes, u are correct ,if u use pycharm ,it will show u the 'string' is a python class,but the 'str' is a data type like 'int'
