### ISSUE TITLE
Get messages from folder is not working

### ISSUE THREAD

**Issue by possebon** [swimlane/python-office365#3]
I'm testing to get messages from folder using this function from examples:

def simple_by_folder(auth):
    mail = Mail(auth=auth)
    m = mail.get_messages_from_folder('Sent Items')
    print('simple_by_folder {count}'.format(count=(len(m))))
    for message in m:
        print(message.Subject)

When I run it:

`>>> simple_by_folder(auth)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in simple_by_folder
  File "/Users/possebon/workspaces/ibope_mailbox/lib/python3.6/site-packages/office365api/mail/base.py", line 55, in get_messages_from_folder
    response = self.connection.get(url=url, params=params)
  File "/Users/possebon/workspaces/ibope_mailbox/lib/python3.6/site-packages/office365api/connection.py", line 23, in get
    self.validate_response(response)
  File "/Users/possebon/workspaces/ibope_mailbox/lib/python3.6/site-packages/office365api/connection.py", line 19, in validate_response
    raise ConnectionError("{code}: {text}".format(code=code, text=response.text))
requests.exceptions.ConnectionError: 400: {"error":{"code":"ErrorInvalidIdMalformed","message":"Id is malformed."}}`

When I try to get messages from a folder created by the user:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in simple_by_folder
  File "/Users/possebon/workspaces/ibope_mailbox/lib/python3.6/site-packages/office365api/mail/base.py", line 55, in get_messages_from_folder
    response = self.connection.get(url=url, params=params)
  File "/Users/possebon/workspaces/ibope_mailbox/lib/python3.6/site-packages/office365api/connection.py", line 23, in get
    self.validate_response(response)
  File "/Users/possebon/workspaces/ibope_mailbox/lib/python3.6/site-packages/office365api/connection.py", line 19, in validate_response
    raise ConnectionError("{code}: {text}".format(code=code, text=response.text))
requests.exceptions.ConnectionError: 400: {"error":{"code":"RequestBroker-ParseUri","message":"Resource not found for the segment 'My custom folder'."}}`

**Comment by dmikov** [comment]
Sorry, for delay. All these errors seems to come from Microsoft API, were you able to get to the "Sent Items" folder using their API? According to their documentation the name is `SentItems`
https://msdn.microsoft.com/en-us/office/office365/api/mail-rest-operations

**Comment by dmikov** [comment]
No reply
