### ISSUE TITLE
Unable to send an email after upgrade to Python 3.7

### ISSUE THREAD

**Issue by rafalbilski** [swimlane/python-office365#7]
Traceback (most recent call last):
  File "tmp.py", line 14, in <module>
    mail.send_message(message)
  File "/usr/lib/python3.7/site-packages/office365api/mail/base.py", line 76, in send_message
    data = message.data
  File "/usr/lib/python3.7/site-packages/office365api/model/model.py", line 59, in data
    return {self.__class__.__name__: dict(self)}
  File "/usr/lib/python3.7/site-packages/office365api/model/model.py", line 8, in __getattr__
    return self[name]
TypeError: 'Message' object is not subscriptable

Your code worked fine in Python 3.6. Thanks!
By trial and error I found out that modification below fixes this issue for Python 3.7. I didn't test it on any other Python versions as code only runs on one dedicated server.

class Model(object):

    def __getattr__(self, name):
        try:
            **return super().getattr(name)**
        except KeyError:
            raise AttributeError(name)

**Comment by rafalbilski** [comment]
Sorry about that it supposed to be bold not **return super().getattr(name)**

**Comment by rafalbilski** [comment]
This markdown styling doesn't work as expected ;)
